# Generated by Django 2.1.5 on 2019-02-22 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20190221_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.UserProfile'),
        ),
    ]
