# Generated by Django 2.1.5 on 2019-02-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20190221_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='win_loss',
        ),
        migrations.AddField(
            model_name='bet',
            name='win',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
