# Generated by Django 2.1.5 on 2019-02-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_auto_20190221_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbet',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='userbet',
            old_name='user',
            new_name='userprofile',
        ),
    ]
