# Generated by Django 2.1.5 on 2019-03-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_username'),
        ('bets', '0005_auto_20190225_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeam', models.CharField(max_length=200)),
                ('awayteam', models.CharField(max_length=200)),
                ('eventdate', models.DateField()),
                ('homescore', models.IntegerField(default=0)),
                ('awayscore', models.IntegerField(default=0)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSportBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_away', models.BooleanField()),
                ('ammount', models.IntegerField()),
                ('sportbet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bets.SportBet')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.UserProfile')),
            ],
        ),
    ]
