# Generated by Django 2.1.5 on 2019-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_sportbet_usersportbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportbet',
            name='idofapi',
            field=models.IntegerField(default=None),
        ),
    ]
