# Generated by Django 2.1.5 on 2019-03-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_sportbet_idofapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportbet',
            name='awaycity',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportbet',
            name='homecity',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
