# Generated by Django 2.1.5 on 2019-03-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20190303_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersportbet',
            old_name='home_away',
            new_name='home',
        ),
    ]
