# Generated by Django 2.1.5 on 2019-03-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_auto_20190305_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersportbet',
            name='odds',
            field=models.FloatField(default=1.0),
        ),
    ]
