# Generated by Django 2.1.5 on 2019-03-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0012_futurebet'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurebet',
            name='team',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
