# Generated by Django 2.1.5 on 2019-03-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0014_futurebet_fractional'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurebet',
            name='league',
            field=models.CharField(default='NBA', max_length=10),
            preserve_default=False,
        ),
    ]
