# Generated by Django 2.1.5 on 2019-06-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0015_futurebet_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportbet',
            name='league',
            field=models.CharField(default='NBA', max_length=100),
            preserve_default=False,
        ),
    ]
