# Generated by Django 2.1.5 on 2019-06-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0016_sportbet_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurebet',
            name='source',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportbet',
            name='source',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
