# Generated by Django 2.1.5 on 2019-06-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0018_usersportbet_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersportbet',
            name='sportbet',
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='awaycity',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='awayscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='awayteam',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='homecity',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='homescore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='hometeam',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='idofapi',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='usersportbet',
            name='league',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
