# Generated by Django 2.1.5 on 2019-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0019_auto_20190610_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometeam', models.CharField(max_length=200)),
                ('homecity', models.CharField(max_length=200)),
                ('awayteam', models.CharField(max_length=200)),
                ('awaycity', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('homescore', models.IntegerField(default=0)),
                ('awayscore', models.IntegerField(default=0)),
                ('completed', models.BooleanField()),
                ('idofapi', models.IntegerField(default=None)),
                ('league', models.CharField(max_length=100)),
            ],
        ),
    ]
